# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
jobs:
  test-lastest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: cd test; ./argp.source_test.sh

  test-16.04:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: cd test; ./argp.source_test.sh
